/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds_data.h
  Source: dds_data.idl
  Cyclone DDS: V0.10.0

*****************************************************************/
#ifndef DDSC_DDS_DATA_H
#define DDSC_DDS_DATA_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_OCTET_DEFINED
#define DDS_SEQUENCE_OCTET_DEFINED
typedef struct dds_sequence_octet
{
  uint32_t _maximum;
  uint32_t _length;
  uint8_t *_buffer;
  bool _release;
} dds_sequence_octet;

#define dds_sequence_octet__alloc() \
((dds_sequence_octet*) dds_alloc (sizeof (dds_sequence_octet)));

#define dds_sequence_octet_allocbuf(l) \
((uint8_t *) dds_alloc ((l) * sizeof (uint8_t)))
#endif /* DDS_SEQUENCE_OCTET_DEFINED */

typedef struct DDSData_Msg
{
  char * topic;
  double timestamp;
  dds_sequence_octet payload;
} DDSData_Msg;

extern const dds_topic_descriptor_t DDSData_Msg_desc;

#define DDSData_Msg__alloc() \
((DDSData_Msg*) dds_alloc (sizeof (DDSData_Msg)));

#define DDSData_Msg_free(d,o) \
dds_sample_free ((d), &DDSData_Msg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_DATA_H */
